// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEntriesForScrape = `-- name: GetEntriesForScrape :many
SELECT uid, data
FROM leaderboard_entries
WHERE scrape_id = $1
`

type GetEntriesForScrapeRow struct {
	Uid  int32  `json:"uid"`
	Data []byte `json:"data"`
}

func (q *Queries) GetEntriesForScrape(ctx context.Context, scrapeID int64) ([]GetEntriesForScrapeRow, error) {
	rows, err := q.db.Query(ctx, getEntriesForScrape, scrapeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntriesForScrapeRow
	for rows.Next() {
		var i GetEntriesForScrapeRow
		if err := rows.Scan(&i.Uid, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestScrapes = `-- name: GetLatestScrapes :many
SELECT scrape_id, leaderboard_kind, scraped_at
FROM leaderboard_scrapes
WHERE leaderboard_kind = $1
ORDER BY scraped_at DESC
LIMIT $2
`

type GetLatestScrapesParams struct {
	LeaderboardKind string `json:"leaderboard_kind"`
	Limit           int32  `json:"limit"`
}

func (q *Queries) GetLatestScrapes(ctx context.Context, arg GetLatestScrapesParams) ([]LeaderboardScrape, error) {
	rows, err := q.db.Query(ctx, getLatestScrapes, arg.LeaderboardKind, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaderboardScrape
	for rows.Next() {
		var i LeaderboardScrape
		if err := rows.Scan(&i.ScrapeID, &i.LeaderboardKind, &i.ScrapedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScrapesInRange = `-- name: GetScrapesInRange :many
SELECT scrape_id, leaderboard_kind, scraped_at
FROM leaderboard_scrapes
WHERE leaderboard_kind = $1
    AND scraped_at BETWEEN $2 and $3
ORDER BY scraped_at ASC
`

type GetScrapesInRangeParams struct {
	LeaderboardKind string             `json:"leaderboard_kind"`
	ScrapedAt       pgtype.Timestamptz `json:"scraped_at"`
	ScrapedAt_2     pgtype.Timestamptz `json:"scraped_at_2"`
}

func (q *Queries) GetScrapesInRange(ctx context.Context, arg GetScrapesInRangeParams) ([]LeaderboardScrape, error) {
	rows, err := q.db.Query(ctx, getScrapesInRange, arg.LeaderboardKind, arg.ScrapedAt, arg.ScrapedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaderboardScrape
	for rows.Next() {
		var i LeaderboardScrape
		if err := rows.Scan(&i.ScrapeID, &i.LeaderboardKind, &i.ScrapedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEntry = `-- name: InsertEntry :exec
INSERT INTO leaderboard_entries (scrape_id, uid, data)
VALUES ($1, $2, $3)
`

type InsertEntryParams struct {
	ScrapeID int64  `json:"scrape_id"`
	Uid      int32  `json:"uid"`
	Data     []byte `json:"data"`
}

func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) error {
	_, err := q.db.Exec(ctx, insertEntry, arg.ScrapeID, arg.Uid, arg.Data)
	return err
}

const insertScrape = `-- name: InsertScrape :one
INSERT INTO leaderboard_scrapes (leaderboard_kind, scraped_at)
VALUES ($1, now())
RETURNING scrape_id
`

func (q *Queries) InsertScrape(ctx context.Context, leaderboardKind string) (int64, error) {
	row := q.db.QueryRow(ctx, insertScrape, leaderboardKind)
	var scrape_id int64
	err := row.Scan(&scrape_id)
	return scrape_id, err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (uid, username)
VALUES ($1, $2)
ON CONFLICT (uid) DO UPDATE SET username = EXCLUDED.username
`

type UpsertUserParams struct {
	Uid      int32  `json:"uid"`
	Username string `json:"username"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.Exec(ctx, upsertUser, arg.Uid, arg.Username)
	return err
}
